screwdriver-cd/scm-github

README.md, index.js, package.json, test/index.test.js
Moving most of the code from models
=> Implementing all the function in the scm-base class

index.js, package.json, test/index.test.js
Requires https://github.com/screwdriver-cd/data-schema/pull/32
=> optional url for commit status

index.js, test/index.test.js
I added `getId` implementation for screwdriver-cd/screwdriver#160 and screwdriver-cd/scm-base#5
=> Add getId function

index.js, package.json, test/index.test.js, wercker.yml
Adds a fun message and the job name (if passed).
Blocked by https://github.com/screwdriver-cd/scm-base/pull/7
=> [3] Adding more information into the commit status

index.js, package.json, test/index.test.js
Updates circuit-fuses to include retry logic.
Adds function to not retry when getFile command fails.
=> do not retry on getFile failure

index.js
An extension of PR #16 
This is to implement `circuit-fuses` new Promise interface.
=> Implement promise interface with circuit-fuses

index.js, test/index.test.js
- Allow getFile from a prRef
- Update tests for https://github.com/screwdriver-cd/data-schema/commit/16405d3d94f64bc9e085834ff2944b1bc33a6292
e.g. `git@github.com:screwdriver-cd-test/functional-git.git#pull/453/merge`
=> Fix bug to take in ref to getFile()

index.js, test/index.test.js
Should not include the first part anymore
=> Make prRef be the short version

README.md, index.js, package.json, test/index.test.js
Depends on https://github.com/screwdriver-cd/scm-base/pull/20
New Features:
- Validates input (breaking change)
- Accepts GitHub Enterprise configuration
- Returns Bell authentication config
=> Validating SCM input, accepting GHE, and returning Bell authentication

index.js, package.json, test/index.test.js
Because of https://github.com/screwdriver-cd/data-schema/pull/81
=> Add hookId to parseHook

package.json
=> [8]Pull in v15 data-schema

index.js, test/index.test.js
Relates to screwdriver-cd/screwdriver#297
=> Better error message when repo does not exist

CHANGELOG.md, index.js, test/data/commands.json, test/data/prCommands.json
Use SCM_USERNAME and SCM_ACCESS_TOKEN to checkout
These can be set as secrets. If they are not set, then just checkout normally
=> Use SCM_USERNAME and SCM_ACCESS_TOKEN to checkout

package.json, screwdriver.yaml
- remove semantic-release from devDependencies
- install only semantic-release before publish
=> fix: remove semantic-release from devDependencies

package.json
=> fix: Update joi to version 10.0.5

index.js, test/index.test.js
Implement a non-public(ish) method that adds a webhook to a repository. If the repo already has a Screwdriver webhook, it will also update the webhook to ensure it has all the correct information (e.g., webhook API secret).
Related to screwdriver-cd/screwdriver#379
=> feat: internal addWebhook method

README.md, index.js, test/data/customPrCommands.json, test/index.test.js
I want to use own username and email for checkout from GHE.
=> fix: can settings username and email for ghe checkout

index.js, test/index.test.js
Implement  `_getPrInfo` function:
Reference about github API to get a single pull request:
https://developer.github.com/v3/pulls/#get-a-single-pull-request
Blocked by https://github.com/screwdriver-cd/scm-base/pull/39
Related to https://github.com/screwdriver-cd/screwdriver/issues/244
=> feat: add _getPrInfo function

index.js, test/index.test.js
Related: https://github.com/screwdriver-cd/screwdriver/issues/471
=> fix: commit context includes pipelineId

screwdriver.yaml
Need a code change to trigger semantic release
Related to https://github.com/screwdriver-cd/scm-github/pull/83
=> feat: Use new workflow. BREAKING CHANGE: bump major

index.js, package-lock.json, package.json, test/index.test.js
add decorate function for new PR field. Uses github api and breaker to retrieve the url.
related pr: https://github.com/screwdriver-cd/screwdriver/issues/822
=> add decorate PR to git scm

index.js, package-lock.json, package.json, test/index.test.js
To get pipelines, we need a function which get list of branch.
Implement getBranchList function.
[octkit/rest api](https://octokit.github.io/rest.js/#api-Repos-getBranches)
Blocked by 
- https://github.com/screwdriver-cd/data-schema/pull/240
- https://github.com/screwdriver-cd/scm-base/pull/57
Related to screwdriver-cd/screwdriver#1082
=> feat(1082): [4] implement getBranchList function

index.js, test/index.test.js
We used scmInfo which is passed from pipeline model to reduce querying github. But scmInfo cannot be passed from pipeline model. Pipeline model passes scmRepo instead of scmInfo, we fixed to use it in scm-github.
scmInfo can be constructed from scmRepo. Therefore, we fixed to construct lookupScmUri's return value from scmRepo without querying github if scmRepo is passed. 
original issue: screwdriver-cd/screwdriver#1220
related PRs:
data-schema: screwdriver-cd/data-schema#277
models: screwdriver-cd/models#288
PR build fails until data-schema is merged screwdriver-cd/data-schema#277 .
=> fix(1220): Use scmRepo instead of querying github

index.js, package.json, test/index.test.js
- add getOrgPermissions function
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1319
=> fix(1319): add getOrgPermissions function

index.js, test/index.test.js
related: https://github.com/screwdriver-cd/screwdriver/issues/1419
related: https://github.com/screwdriver-cd/ui/pull/395
blocked by: https://github.com/screwdriver-cd/scm-base/pull/67
blocked by: https://github.com/screwdriver-cd/data-schema/pull/309
=> fix: more pr & author info

index.js, package.json, test/index.test.js
blocked by: https://github.com/screwdriver-cd/data-schema/pull/324
related: https://github.com/screwdriver-cd/screwdriver/issues/1528
=> fix: add getting changed files for PR

index.js, package.json, test/index.test.js
https://github.com/screwdriver-cd/screwdriver/issues/1510
This PR fixes the logic to deal with pagination and fetch all pages of results instead of just the first page with 30 results.
=> fix: Deal with pagination of response for modified PR files

index.js, package.json, test/index.test.js
Refactor logging
Properly initialize log level
=> fix: refactor logging

index.js
~~Wait a little for the merge. I am just checking the operation.~~
As a result of running in my environment, no problem was found in operation.
However, the UI also needed one modification, so I created a PR. https://github.com/screwdriver-cd/ui/pull/521
This PR is for this Issue.
https://github.com/screwdriver-cd/screwdriver/issues/1925
=> fix(1925): support name of branch with '#'

index.js, package.json, test/index.test.js
Adding a new method openPr in scm plugin
Adding a new method openPr in scm plugin
https://github.com/screwdriver-cd/screwdriver/issues/1922
=> feat(1922): add openPr method. BREAKING CHANGE: pulling in latest scm-base

index.js
currently our sshHost validation hardcodes the pattern
refactor to use checkoutUrl regex instead
https://github.com/screwdriver-cd/screwdriver/issues/2017
=> fix(2017): sshHost validation

index.js, test/index.test.js
Users might not have `master` as their default branch in Github. When a branch is not specified, we should use the user's default branch instead of hardcoding to `master`.
This PR uses the user's default branch instead of `master`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2185
=> fix(2185): Use default branch for scmUri instead of hardcoding [1]

.gitignore, index.js, package.json, test/index.test.js
Fixes screwdriver-cd/screwdriver#1415
=> fix(1415): Fix function definition and event map object

index.js, package.json, test/index.test.js
need to fetch repo visibility to support pipeline read protect
fetch repo visibility 
https://github.com/screwdriver-cd/screwdriver/issues/466
=> feat(466): use scmRepo to fetch repo visibility

index.js, test/index.test.js
octokit returns status code as `response.status` or `error.status`.
scm-githbu returns octokit response as is, thus the status code is `response.status` as well.
On the other hand, [scm-gitlab](https://github.com/screwdriver-cd/scm-gitlab) and [scm-bitbucket](https://github.com/screwdriver-cd/scm-bitbucket) use [screwdriver-request](https://github.com/screwdriver-cd/request), so its status code is `response.statusCode`.
Furthermore, other components using breaker (ex: executor-k8s) also use `response.statusCode`.
- Change it to use `statusCode` instead of `status`.
- Add some error code.
- Fix tests.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
=> fix: Use response.statusCode instead of response.status

CONTRIBUTING.md, package.json
=> fix: Semantic release to publish

index.js, package.json, test/data/github.pull_request.createComment.json, test/data/github.pull_request.listComment.json, test/index.test.js
https://github.com/screwdriver-cd/screwdriver/issues/2873
=> feat(2873): add support for multi comment

index.js, test/index.test.js
should pass in a string instead of an object
=> fix: fix typo

index.js, test/index.test.js
The following PR needs to get a SCM user id.
https://github.com/screwdriver-cd/screwdriver/pull/2890
This PR will include a GitHub id in the return value of `decorateAuthor`.
This PR will add a GitHub id in the return value of `decorateAuthor`.
Please review the following PR first, tests will be corrected by the PR.
- https://github.com/screwdriver-cd/data-schema/pull/518
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/2892
=> [2] feat(2892): get GitHub user ID

package.json
Update scm-base version
Update scm-base version
=> feat: update scm-base version

package.json
Deploy new version of `scm-github`
Deploy new version of `scm-github`
https://github.com/screwdriver-cd/scm-github-graphql/pull/3
=> feat: deploy new version of scm-github

index.js, test/index.test.js
When JSON.stringify() is applied to certain control characters, their character representation changes.
```
> JSON.stringify({x: '\u001F'})
'{"x":"\\u001f"}'
> JSON.stringify({x: '\x1F'})
'{"x":"\\u001f"}'
```
Therefore, if you use the value obtained by re-stringifying the payload after JSON.parse for verifying the signature, it will fail because the contents do not match.
- The original payload will be used for signature verification.
- Enable passing the string before parsing to the _parseHook in scm components.
- https://github.com/screwdriver-cd/scm-base/pull/102
- https://github.com/screwdriver-cd/scm-github/pull/250
- https://github.com/screwdriver-cd/scm-gitlab/pull/74
- https://github.com/screwdriver-cd/scm-bitbucket/pull/102
- https://github.com/screwdriver-cd/scm-router/pull/39 …
=> fix: Verify signature of payloads containing control characters [2]
