screwdriver-cd/scm-github

- README.md
- index.js
- package.json
- test/index.test.js
This PR adds in the implementation of the `getFile` function
It takes in an scmUrl, token, path and a reference and will return the contents of the file that is found on github.
We probably needs to come up with an error translation function
> Adding getFile implementation

- README.md
- index.js
- test/index.test.js
This PR is adding in a `stats` function for exposing circuit breaker statistics for the api
The breaker stats are exposed via circuit-fuses: https://github.com/screwdriver-cd/circuit-fuses#get-total-number-requests
> Overriding stats function (merge #2)

- test/index.test.js
The previous PR tests failed in wercker because it was actually trying to evaluate the averateRequestTime.
This value seemed to flip between `0` and `1` probably due to what clock cycle the yieldAsync happens.
This PR tests the stat values individually instead of with a deepEqual
> Stats test was not deterministic

- index.js
The `github.authenticate` function stores the token for the subsequent github request.
This PR is moving the authenticate to be right before the github request to ensure that the call to github is using the correct token
https://github.com/mikedeboer/node-github#authentication
> moving where we authenticate with the token

- index.js
- package.json
- test/index.test.js
This PR is pulling in the new version of `circuit-fuses` that supports native retries
Fix the stats tests to make a call that succeeds instead of fails.
> Use new circuit-fuses that supports retries

- README.md
- index.js
- package.json
- test/index.test.js
This PR has `scm-github` adopt the new v2 `scm-base` interface. This switches the use of `scmUrl` with `scmUri`, as well as additional methods for decorating data.
Resolves #15
> Implement v2 interface

- index.js
- package.json
- test/index.test.js
- `author` should come from *author* login, not *committer* login
- `getCommit` requires `user` as a param, not `owner` (in this version of the github module)
- some devDependencies are very behind
NOTE: will bump `github` version in a different pull request
> Fix author lookup, bump dependency versions

- index.js
- test/index.test.js
It is currently possible for `displayName` to be null, which will break the `data-schema`
Defaulting `displayName` value to `username`
> If display name does not exist, default to username

- README.md
- index.js
- package.json
- test/index.test.js
#As per St.John's suggestions to decouple Screwdriver API from Github
- adds Github webhook signing secret to constructor
- adds checkSignature method in parseHook
Related to https://github.com/screwdriver-cd/screwdriver/pull/313
> Add github webhook signing secret to constructor; add checkSignature() to parseHook()

- CHANGELOG.md
- index.js
- package.json
- test/index.test.js
Screwdriver API uses github package v5, but the scm-github repo is still on v3. Updating scm-github so the two are using the same version.
> Bump github npm package to v6

- index.js
- test/index.test.js
- v6 github requires `username` as key instead of `user`
- http://mikedeboer.github.io/node-github/#api-orgs-getForUser
> Fix bug: v6 getForUser requires params with username as key

- index.js
- test/index.test.js
Proposal to fix screwdriver-cd/screwdriver#344
When looking up a commit, it is assumed that the user exists in the github instance. This PR proposes to address this by filling in dummy data.
> Gracefully handle missing user

- CHANGELOG.md
- index.js
- package.json
- test/data/commands.json
- test/data/prCommands.json
- test/index.test.js
The launcher is currently hardcoded to checkout repositories from github.com. We want to move that logic into the scm plugins. Adding a method to get checkout commands in the scm-github.
Related to https://github.com/screwdriver-cd/scm-base/pull/28
Related to https://github.com/screwdriver-cd/screwdriver/issues/312
> Add method to get checkout commands

- index.js
- package.json
- test/data/commands.json
- test/data/prCommands.json
Adding `sd-` as a prefix for the command name to avoid stepping on user configs
Blocked by https://github.com/screwdriver-cd/scm-base/pull/29
> [3] Checkout command name should be sd-checkout-code

- index.js
- test/data/commands.json
- test/data/prCommands.json
- Switching to using an absolute path when running `git clone` so the src dir will be consistent in the launcher
- SD_SOURCE_DIR is an environment variable set in the launcher
https://github.com/screwdriver-cd/launcher/blob/master/launch.go#L236
Related to https://github.com/screwdriver-cd/screwdriver/issues/312
> Use absolute path for git clone

- README.md
- package.json
- screwdriver.yaml
- use `semantic-release` to bump version, publish to npm and push tags back to github
- changed the REAMED to make it consistent with scm-bitbucket
> fix: use semantic-release to publish

- package.json
Breaking changes do not affect us. 
Release note: https://github.com/mikedeboer/node-github/blob/master/CHANGELOG.md
Related https://github.com/screwdriver-cd/screwdriver/pull/383/files
> fix: update github to v7

- index.js
- test/.eslintrc.yaml
- test/index.test.js
Implementing the `_getOpenedPRs` method that was introduced with screwdriver-cd/scm-base#37. 
This will look up the opened PRs against a specific repository. It will then return a payload of a few data points `name`, `prRef`.
Related to screwdriver-cd/screwdriver#417
> Implementing _getOpenedPRs

- index.js
- test/index.test.js
Granting `repo` for oauth app:
Grants read/write access to code, commit statuses, invitations, collaborators, adding team memberships, and deployment statuses for public and private repositories and organizations.
Resolves https://github.com/screwdriver-cd/screwdriver/issues/436
> feat: Grant access to private repo

- package.json
Update this to be up to date with the API: https://github.com/screwdriver-cd/screwdriver/blob/master/package.json#L103
> fix: update github dependency to version 8

- index.js
- test/index.test.js
This resolves https://github.com/screwdriver-cd/screwdriver/issues/594
@stjohnjohnson  I'm not adding `pipelineId` because it's not available in the param. If we want that, we would need to change it in the model. I think `Screwdriver/main` or `Screwdriver/PR` is sufficient.
> fix: change commit context for PR jobs

- index.js
- test/data/github.push.json
- test/index.test.js
I'd like to implement the skipping builds feature (screwdriver-cd/screwdriver#587)
This PR adds lastCommitMessage to the result of `parseHook`.
If this PR is approved, I'll change [around this code](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/index.js#L397) to check if the last commit message contains "[skip ci]". I'll also change other scm plugins.
- issue: screwdriver-cd/screwdriver#587
- webhook spec: https://developer.github.com/v3/activity/events/types/#pushevent
> feat(587): Add lastCommitMessage to parsed hook

- index.js
- test/index.test.js
A user uses multiple jobs triggered by pull request like this:
Only `Screwdriver/<pipeline_id>/PR` status is created and updated when the user open pull request. This causes when the first pull request job is finished then the status become `success` in spite of other builds running. 
I think multiple statuses should be created and updated for checking PR job statuses individually.
~~Use jobName directly in the context.~~
Use jobName in the context like: `Screwdriver/123/PR:test`
GitHub API: https://developer.github.com/v3/repos/statuses/#create-a-status
> fix: use jobName as context on create status

- index.js
- test/index.test.js
From https://developer.github.com/v3/repos/statuses/
>Note: there is a limit of 1000 statuses per sha and context within a repository. Attempts to create more than 1000 statuses will result in a validation error.
There are build monitoring pipelines that run periodically, and reach the limit noted above. When the error is thrown, the pipeline stops entirely. See the [old PR](https://github.com/screwdriver-cd/models/pull/228) for full error.
Allow pipelines to continue if the 1000 statuses per SHA limit is reached.
* Issue: https://github.com/screwdriver-cd/screwdriver/issues/881
* Old PR: https://github.com/screwdriver-cd/models/pull/228
> fix(881): Ignore errors from github with error code 422

- index.js
- package.json
- test/data/github.pull_request.files.json
- test/index.test.js
We'd like to add a method that gets a list of changed files when a push or PR occurs in Git. This will allow for subdirectory support.
This PR:
- adds **getChangedFiles** method
Note: probably want to bump major version
- Blocked by https://github.com/screwdriver-cd/data-schema/pull/215, https://github.com/screwdriver-cd/scm-base/pull/49
- Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911
> feat(911): Add getChangedFiles [3]

- index.js
- test/data/github.push.json
- test/index.test.js
There's also `added` and `removed` files that might be changes for a push event in Github.
This PR adds those files to `getChangedFiles` results.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911
> fix(911): Also check added and removed files for sourcePaths

- index.js
- package.json
- screwdriver.yaml
- test/index.test.js
Node.js 6 is slowly becoming deprecated, with popular packages such as `semantic-release` no longer supporting it. Aside from maintenance, upgrading to Node.js 8 also provides async functions, which simplify `Promise` control flow.
* Change image in `screwdriver.yaml` to `node:8`
* Convert functions that return a `Promise` to `async` functions
* Bump up coverage to 100%
* Remove empty `test.js` file
> refactor(hip): Upgrade to node:8

- index.js
- package.json
- test/index.test.js
We were many versions behind on a github npm module we were using.
This PR pulls in the latest version of `@octokit/rest` and updates code to comply.
- Most changes come from v9.0.0: https://github.com/octokit/rest.js/blob/f4845cffb392fcb0671d70e1e2779eabe0c8fd12/CHANGELOG.md#900
Responses before:
```
{
repo: 'mytest',
owner: 'tkyi'
}
```
Responses now:
```
{ 
data: {
repo: 'mytest',
owner: 'tkyi'
} 
}
```
- GHE support: Can no longer pass in `gheHost`, `gheProtocol`, and `pathPrefix` to the config, need to use `baseUrl` instead (https://www.npmjs.com/package/@octokit/rest#client-options)
- `editHook` takes in `hook_id` now vs `id` before (https://octokit.github.io/rest.js/#api-Repos-editHook)
- Don't need to pass in `host` to `getBranch`
- Updated tests to match
Issue: …
> feat(1042): Update github module to @octokit/rest. BREAKING CHANGE: updating major versions

- index.js
- package.json
- test/index.test.js
Currently, if a Pipeline contains  **suspended** admins, its build starting fails with the following UI error message.
```
{"message":"Sorry. Your account was suspended.","documentation_url":"https://developer.github.com/enterprise/2.11/v3"}
```
It is caused by the 403 response of the GitHub API for suspended users.
This PR catches the 403 exception and returns a normal permission object (`{admin: false, push: false, pull: false}`, which means unauthorized).
- https://github.com/screwdriver-cd/screwdriver/issues/854
> fix(854): [small] normalize suspended user's permissions.

- index.js
- test/index.test.js
Currently, exceptions for unexpected GitHub API responses are almost thrown to the API and UI layer and NOT logged. It causes too difficult to debug it about GitHub problems.
This PR enables logging unexpected exceptions and re-throwing it.
> refactor: [small] add logging unexpected runtime exceptions.

- index.js
- test/index.test.js
The error object for suspended user access does not have any status code (e.g. 403, 404)!
We should check the error message alone.
- Error log sample
```
error:  message={"message":"Sorry. Your account was suspended.","documentation_url":"https://developer.github.com/enterprise/2.11/v3"}, stack=HttpError: {"message":"Sorry. Your account was suspended.","documentation_url":"https://developer.github.com/enterprise/2.11/v3"}
at response.text.then.message (/usr/src/app/node_modules/@octokit/rest/lib/request/request.js:78:19)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7), name=HttpError, code=403, status=undefined, access-control-allow-origin=*, access-control-expose-headers=ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, …
```
> fix: fix suspended user check.

- index.js
- test/index.test.js
I did a careless mistake. :disappointed:
We can not access the `scmInfo` object by a suspended user. This PR fixes log output and improve the test case.
> fix: [small] fix log output and the test case for suspended users.

- index.js
- test/index.test.js
Screwdriver calls `lookupScmUri many times during a single PR event and it should be reduced.
This PR changes `getFile`, `decorateUrl` and `getPrInfo` to accept optional `scmInfo` object and use it instead of calling `lookupScmUri`.
original issue: screwdriver-cd/screwdriver#1220
blocked by https://github.com/screwdriver-cd/data-schema/pull/273
> [2] fix(1220): Reduce API calls

- index.js
- package.json
- test/data/github.pull_request.createComment.json
- test/index.test.js
It would be nice for users to be able to comment back on PRs through a build with relevant metadata.
This PR adds a method to add a PR comment.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1355
Blocked by scm-base
> feat(1355): Add method to add PR comment [4]

- index.js
- test/index.test.js
The call to `addPrComment` makes the build hang when it fails.
This PR returns null instead of throwing an error when cannot add PR comment to Github.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1355
> fix(1355): Do not throw error when cannot add PR comment

- .eslintignore
- index.js
- test/index.test.js
Need `public_repo` scoped token to make a PR comment. The most secure solution is to add a `token` to scm settings that had no specific access to repos but has that scope.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1355
> fix(1355): Use token from config

- index.js
If there is an error parsing a webhook, canHandleWebhook just returns false and we cannot know the reason why it failed.
* Print error log with an error object after the error is caught
> Fix: Add error log

- index.js
- test/index.test.js
Users would like to add custom Git statuses for commits.
This PR adds `context` and `description` fields to be passed into the `scm.updateCommitStatus` method. The `context` will be the key provided by the user. `description` will be the message they want to show.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1440
Blocked by https://github.com/screwdriver-cd/data-schema/pull/307
> feat(1440): Use custom context and description to updateCommitStatus [3]

- index.js
- test/index.test.js
We want to add pr title to the event for using it in notification.
Add prTitle to _parseHook return when the github-event type is pull_request.
Related PRs:
data-shema https://github.com/screwdriver-cd/data-schema/pull/310
models https://github.com/screwdriver-cd/models/pull/321
screwdriver https://github.com/screwdriver-cd/screwdriver/pull/1456
CI test will pass after https://github.com/screwdriver-cd/data-schema/pull/310 is merged.
> [3] feat: Add pr title to the event

- index.js
- package.json
- test/index.test.js
There are many deprecations between octokit 15.x and 16.x. So [the api document](https://octokit.github.io/rest.js/) is hard to read.
This PR updates octokit to 16.x.
We also should think about using [octokit throttling](https://github.com/octokit/rest.js#throttling) instead of circuit breaker retry.
- [deprecations list](https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations)
- [Release v16.0.1 (including Breaking changes list)](https://github.com/octokit/rest.js/releases/tag/v16.0.1)
- [Alias legacy scopes for backwards compatibility by gr2m · Pull Request #1135 · octokit/rest.js](https://github.com/octokit/rest.js/pull/1135)
> feat: update octokit to 16.x  BREAKING CHANGE: updating major versions

- index.js
- package.json
- test/index.test.js
add committer to decorateCommit
example commit payload from github: https://developer.github.com/v3/repos/commits/#get-a-single-commit
Related to https://github.com/screwdriver-cd/screwdriver/issues/1437
> feat: add committer to decorateCommit

- index.js
- test/index.test.js
`number` is deprecated. `sha` is deprecated.
seeing this in logs:
```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".pulls.get()". Use "pull_number" instead
at Object.keys.forEach.key (/usr/src/app/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:73:26)
at Array.forEach (<anonymous>)
{ Deprecation: [@octokit/rest] "sha" parameter is deprecated for ".repos.getCommit()". Use "commit_sha" instead
```
> fix: use pull_number instead of number

- index.js
add err logs for getBranchList, other functions all have it
> fix: add err logs for getBranchList

- index.js
- test/index.test.js
SD can execute release/tag trigger, but it can't provide release/tag info(ex. name).
SD user want to get release/tag info.
Add some release fields to returned value from parseHook when release action is hooked.
https://github.com/screwdriver-cd/screwdriver/issues/823#issuecomment-490014132
This PR is blocked by these PRs.
https://github.com/screwdriver-cd/data-schema/pull/337
> fix(823): [2] Add some release fields for parseHook

- index.js
- test/index.test.js
shouldn't use Path.join with http protocol part.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1455
> fix(1455): fix scm url with rootDir

- index.js
- test/index.test.js
**Issue #, if available:** https://github.com/screwdriver-cd/screwdriver/issues/1646
When `pipeline.prSync` is called, it needs base branch info for the PR to get next job for `~pr:<branchName>`.
**Description of changes:**
This PR allow `getPrInfo` to return `baseBranch` value which contains the base branch name of a PR.
This PR is requires below changes before merge.
https://github.com/screwdriver-cd/scm-base/pull/70
https://github.com/screwdriver-cd/data-schema/pull/339
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.
> fix(1646): [3] add baseBranch to return value in getPrInfo

- index.js
- package.json
- test/index.test.js
We found 5 deprecation messages at log 
```
{ Deprecation: [@octokit/rest] "commit_sha" parameter is deprecated for ".repos.getCommit()". Use "ref" instead
{ Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead
{ Deprecation: [@octokit/rest] "Get the SHA-1 of a commit reference" will be removed. Use "Get a single commit" instead with media type format set to "sha" instead.
```
and only when  node version is 10 of higher
```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
We fixed deprecations …
> fix: deprecation of octokit and Node Buffer API

- index.js
- test/index.test.js
getCommitRefSha function can't get sha correctly when tag name and branch name are same.
This PR change `getCommit` action to `getRef` action, and add 'refType' param 
[octokit/rest getRef](https://octokit.github.io/rest.js/#octokit-routes-git-get-ref)
[data-schema PR](https://github.com/screwdriver-cd/data-schema/pull/347)
> fix: [2] Use 'getRef' instead of 'getCommit' in 'getCommitRefSha'

- index.js
- package.json
- test/index.test.js
Currently there's a mismatch in v3 and v4 ci skip logic. To change v4 ci skip logic to match v3 we need to parse an additional field from webhook payload.
parse an additional field 'commit authors' from webhook payload
screwdriver-cd/screwdriver#1747
> fix(1747) : parse commit authors from webhook payload

- index.js
- test/index.test.js
fix bug that sd cannot fire annotated tag trigger.
When refSha API return type of `tag`, sd call getTag API and get commit sha. It is because refSha API returns tag_sha when the type is `tag`.
https://github.com/screwdriver-cd/screwdriver/issues/1764
> fix(1764): able to handle annotated tag

- index.js
- test/index.test.js
Sometimes when there are PRs with over 2500 files changed, the webhook will fail since the circuit breaker will timeout.
This PR does not throw errs when `getChangedFiles` or `getOpenedPrs` calls fail.
Short term fix for: https://github.com/screwdriver-cd/screwdriver/issues/1769
> fix(1769): Do not throw err if cannot get changed files

- package.json
Because don't import breaking change about [#1816](https://github.com/screwdriver-cd/screwdriver/issues/1816)
- Pined version to `16.33.x`
- Support old API about request URL
https://github.com/screwdriver-cd/screwdriver/issues/1816
https://github.com/octokit/rest.js/commit/e891d4e31c41e7a6afe0c8257404bf1f51607f5e#diff-0071a9eb9e809c9aacfc547f7514add6L1066
> fix(1816): Fix package.json

- index.js
Fixes screwdriver-cd/screwdriver#1714
Before this, when multiple builds took place, it resulted in multiple meta PR comments. To tackle that, the comments for that PR is listed and if a bot comment is found, it is edited, else a new comment is created.
screwdriver-cd/screwdriver#1714
> feat(scm-github): Allow editing of existing PR bot comments

- index.js
- test/index.test.js
When PR builds are restarted by API call, prSource information is disappear.
Because of this, restarted PR builds cannot trigger next Jobs.
Tests are failed until screwdriver-cd/scm-base#78 is merged.
I added prSource to getPrInfo return value.
screwdriver-cd/screwdriver#2029
> fix(2029): [2] Add prSource to prInfo return value

- index.js
- package.json
Currently our custom logic to verify webhook signature breaks SSH Certificate Authorities
Remove our custom logic and use Octokit Webhook's [verify](https://github.com/octokit/webhooks.js/tree/master/src/verify) method instead
https://github.com/screwdriver-cd/screwdriver/issues/2017
> fix(2017): switch to Octokit verify method

- index.js
- test/index.test.js
This PR makes it possible to hundle pipelines of repository which has no `screwdriver.yaml`.
We fixed to return empty file when screwdriver.yaml is not found.
https://github.com/screwdriver-cd/screwdriver/issues/2094
> fix(2094): [1] return empty file when screwdriver.yaml is not found

- index.js
- test/index.test.js
Very rarely, Screwdriver.cd tries to refer to `SHA: 0000000000000000000000000000000000000000`, and GitHub responds with `422 Unprocessable Entity`. Perhaps I think we also need to check for mergeable (like https://github.com/screwdriver-cd/scm-github/pull/1450 ) on `getCommitSha()`.
I want to fix unnecessary access to github with `SHA: 0000000000000000000000000000000000000000`.
https://github.com/screwdriver-cd/screwdriver/issues/1468
> fix: Add mergeable check

- index.js
Pull request with large number of committed files is more prone to timeout from breaker perspective
increase page size to 100, instead of default 30, for the paginated request for pull request files to 1) reduce overall request duration 2) reduce overall chance of getting rate limited
https://developer.github.com/v3/pulls/#list-pull-requests-files
> fix: increase page size for PR files request

- index.js
- package.json
- test/index.test.js
Fixes screwdriver-cd/screwdriver#1079
This PR contains the implementation of the automatic generation of private and public deploy keys and also addition of keys to the scm repo. This PR will automate the deploy key mechanism with getting activated with just a flag.
Fixes screwdriver-cd/screwdriver#1079
> feat(1079): Add key pair generation method and push public key to scm [4]

- index.js
- test/index.test.js
Fixes screwdriver-cd/screwdriver#1079
This PR contains removal of redundant autoDeployKeyGenerationEnabled function
Fixes screwdriver-cd/screwdriver#1079
> fix(1079): Remove unnecessary autoDeployKeyGenerationEnabled function

- index.js
- test/index.test.js
Fixes screwdriver-cd/screwdriver#1079
This PR refactors the addDeployKey method to use the request type format of the createDeployKey.
screwdriver-cd/screwdriver#1079
> refactor(1079): Refactor addDeployKey to use request scope format

- index.js
- package.json
- screwdriver.yaml
- test/index.test.js
Need to update to latest @octokit/rest
This PR updates the octokit package
See release notes for v18: https://github.com/octokit/rest.js/releases/tag/v18.0.0
> fix: update to use latest octokit (v18)

- index.js
- test/data/github.push.deleted.json
- test/index.test.js
Such errors occurs in a situation, and it is noisy in any investigation or analysis.
```
Getting errors with [{"action":"getCommit","token":"248ec46cbf868bfe999bf6590c0ba42ee8cd90a2","params":{"owner":"yoshwata-test","repo":"branch-filter-test","ref":"0000000000000000000000000000000000000000"}}]: HttpError: No commit found for SHA: 0000000000000000000000000000000000000000
```
The situation is
- When a branch is deleted
- the branch is match with the branch filter regex.
`00000` means that deleted branch is not exist anymore.
~~Test will fail before  https://github.com/screwdriver-cd/data-schema/pull/410 is applied.~~
API does not emit `No commit found for SHA: 0000~` error.
https://github.com/screwdriver-cd/data-schema/pull/410
https://github.com/screwdriver-cd/scm-github/pull/179
I …
> fix: noisy logs, no commit found for sha

- index.js
- test/index.test.js
Fixes screwdriver-cd/screwdriver#1415
This PR adds provision for custom actions in addWebhook, to be used while adding multiple webhooks with different actions.
screwdriver-cd/screwdriver#1415
> feat(1415): Add provision for custom actions in addWebhook

- index.js
When we make release choosing from "Recent Commits" , hook's `release.target_commitish` field is not a branch name but a commit sha.
Therefore, `release.target_commitish` field should not be used as a branch.
Because a release references tag when determine build's commit sha and tag hook event uses `repository.default_branch` as a branch, release hook event should better to use `repository.default_branch` as a branch too.
Use `repository.default_branch` field as a branch for hook.
screwdriver-cd/screwdriver#1969
> fix(1969): Fix branch from release hook

- index.js
- package.json
- test/index.test.js
Would be nice if childPipelines could be sourced from somewhere other than checkout root dir.
This PR reads rootDir from checkoutUrl.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2398
> feat(2398): Read rootDir from checkoutUrl [2]

- index.js
Users might want to report on a PENDING status for GitHub PR.
This PR adds pending key for the PR status and description map.
[fix: Allow pending status for GitHub PR meta status check #496
](https://github.com/screwdriver-cd/models/pull/496)
> feat: Allow PENDING status for GitHub PR 

- index.js
If PR is not mergeable, `waitPrMergeability` method will retry `POLLING_MAX_ATTEMPT` times.
I fix `waitPrMergeability` to return false without retrying if it turns out that a PR is not mergeable.
[This document](https://docs.github.com/en/rest/reference/pulls#get-a-pull-request) says that `pullRequestInfo.mergeable` can be `true`, `false`, or `null`.
If `mergeable` is `true`, then the PR is mergeable.
If `mergeable` is `false`, then the PR is NOT mergeable.
If `mergeable` is `null`, then the mergeability is being calculated.
> fix: Exclude unnecessary retries for checking PR mergeability

- package.json
I recently modified scm-git (hab | lab) but got an error when publishing.
https://cd.screwdriver.cd/pipelines/8/builds/749932/steps/publish
https://cd.screwdriver.cd/pipelines/1653/builds/749929/steps/publish
It seems that the noop plugin is no longer needed due to the version upgrade of semantic-release, so the noop plugin will be deleted in this PR.
scm-git(hub|lab) is published.
https://github.com/screwdriver-cd/aws-producer-service/pull/4
> fix: publish error

- index.js
- test/index.test.js
Fixed a bug when scmContext was mismatched in the following PR.
https://github.com/screwdriver-cd/scm-github/pull/194
However, as shown below, an error has occurred when using OpenSource.
https://github.com/screwdriver-cd/scm-github/pull/194#discussion_r750796270
When using OpenSource, `this.config.gheHost` is` undefined`, so set `github.com` as the default value.
Since gitlab has default values ​​set when the object is created, no modification is necessary.
https://github.com/screwdriver-cd/scm-gitlab/blob/e22370a28b41a8236866996ca31a96e978b8b14c/index.js#L135
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
> fix: error occurs on open source

- index.js
- package.json
- test/index.test.js
In order to support getting provider config dynamically in screwdriver.yaml, we need to be able to pass in the full path to getFile instead of the scmUri, etc.
This PR changes getFile method to allow using full path to get repo owner, name, branch, etc info.
https://github.com/screwdriver-cd/screwdriver/issues/2676
> feat(2676): Support passing in full path for getFile [1]

- index.js
- test/index.test.js
If multiple jobs have PR comments, the later job's comment overwrites the earlier job's comment.
We change so that PR comments are only edited by the same job in the same pipeline.
https://docs.github.com/ja/rest/issues/comments#list-issue-comments
https://github.com/screwdriver-cd/screwdriver/issues/2695
Reflect the following PRs before reflecting this.
- https://github.com/screwdriver-cd/data-schema/pull/489
- https://github.com/screwdriver-cd/models/pull/543
> [2]feat(2695): Does not overwrite PR comment that from other PR job

- index.js
- test/index.test.js
Github API to fetch pull requests has default page size of 30
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#pagination
This affects the Pull Request Sync workflow when there are more that 30 open pull requests.
This flow assumes that `getOpenedPRs()` API would return complete list of open pull requests for the specified repo.
When only 30 PRs are returned, the sync flow treats other open PRs are closed and archive the jobs related to them.
Thus preventing any new events/builds against them.
**Short term fix:**
Override the default page size to the maximum allowed size (100)
**Long term fix:**
Iterate over all the pages, consolidate and return the items from all the pages. Need more analysis to see how feasible this would be or find alternative approach.
This PR …
> Fix(2753): Get open pull requests - override the default limit (30) to return up to 100

- index.js
Improve the following Issue.
https://github.com/screwdriver-cd/screwdriver/issues/2734
In this PR, change the Circuit Breaker so that it is not Open even if a 4XX response code is returned from the GitHub
https://github.com/screwdriver-cd/screwdriver/issues/2734
> fix(2734): Builds cannot be started if a pipeline has more than 5 invalid admins

- index.js
- test/index.test.js
Follow up of PR https://github.com/screwdriver-cd/scm-github/pull/216
This PR normalize the type of GitHub user id to String.
https://github.com/screwdriver-cd/screwdriver/issues/2892#issuecomment-1602452632
> fix(2892): normalize the type of GitHub user id to String

- index.js
- package.json
Vulnerability discovered in `@octokit/webhooks`.
Reference: https://github.com/screwdriver-cd/scm-github/pull/221.
`@octokit/webhooks` no longer exports verify methods in version 9, so we are moving to `@octokit/webhooks-methods`.
https://github.com/octokit/webhooks.js/releases/tag/v9.0.0
> fix: upgrade octokit

- index.js
- package.json
- test/index.test.js
Implement API to check for enterprise user
This PR adds a function to determine if a user belongs to an enterprise
https://github.com/screwdriver-cd/scm-github-graphql/pull/1
> feat: add fn to check enterprise user

- index.js
- test/index.test.js
Github GQL queries need additional scopes to query an enterprise 
This PR adds additional scopes to the oAuth token for running GQL queries.
https://docs.github.com/en/enterprise-cloud@latest/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#requested-scopes-and-granted-scopes
> feat: add scopes for GQL query

- index.js
- test/index.test.js
I would like to skip GitHub access if `scmRepo` is available.
https://github.com/screwdriver-cd/screwdriver/issues/3146
Use `scmRepo` to get repository name if it is passed.
Prior PR: https://github.com/screwdriver-cd/data-schema/pull/570
Issue: https://github.com/screwdriver-cd/screwdriver/issues/3146
> feat(3146): Skip requests to GitHub if scmRepo is available [2]

- README.md
- index.js
- package.json
- test/index.test.js
The design of `scm-github` currently supports a single OAuth app for non GHE host (github.com), but with the addition of github cloud we can have multiple enterprise github cloud accounts with same url i.e. https://github.com
This PR adds provision for configuring the scm context and oauth flow based on the github cloud account
> feat: allow github cloud context

- index.js
- test/index.test.js
SD configuration currently does not support pull_request closed trigger, to enable this feature we need to additional parsed information from webhook
This PR adds `prMerged` flag to parsed webhook response
https://github.com/screwdriver-cd/data-schema/pull/597
> feat: add prMerged flag to webhook result
